### ISSUE TITLE
Which version of scanpy and anndata should i use?

### ISSUE THREAD

**Issue by kunwang34** [soedinglab/prosstt#13]
I've read the PROSSTT paper with great interest and find its amazing! 
I'm trying to run examples you provided but theres some error when import scanpy and anndata. I think I didn't choose their version right. Could you please tell me which version should I use?
Thanks a lot.

**Comment by galicae** [comment]
Hi @kunwang34, happy to hear that :) Would you mind posting the full error message here? Otherwise I'm afraid I can't help too much with debugging :(

**Comment by kunwang34** [comment]
Thanks for your reply @galicae.
I'm trying to run the example with scanpy 1.7.2 and anndata 0.7.6.
Here's error:

ImportError                               Traceback (most recent call last)
<ipython-input-3-e7538f39d00d> in <module>
      1 import anndata as ad
----> 2 from scanpy.api import pp
      3 from scanpy.api.tl import diffmap
      4 
      5 # data = ad.AnnData(np.log(X+1))

c:\users\wangkun\miniconda3\envs\prosstt\lib\site-packages\scanpy\api\__init__.py in <module>
     25 
     26 from . import tl
---> 27 from . import pl
     28 from . import pp
     29 from ..readwrite import (

c:\users\wangkun\miniconda3\envs\prosstt\lib\site-packages\scanpy\api\pl.py in <module>
----> 1 from ..plotting._anndata import (
      2     scatter,
      3     violin,
      4     ranking,
      5     clustermap,

ImportError: cannot import name 'stacked_violin'

Thanks again.

**Comment by galicae** [comment]
you are right - these are relics of a previous scanpy version. For the examples to run normally, please remove the `api` from the scanpy imports: instead of `from scanpy.api import pp` just do `from scanpy import pp`. I will amend the notebooks and push again :)

**Comment by kunwang34** [comment]
Thank you very much @galicae . It works.
