### ISSUE TITLE
Simulate gene dropout with PROSSTT

### ISSUE THREAD

**Issue by scottgigante** [soedinglab/prosstt#5]
Have you looked into how to accurately simulate dropout / is this easy to do with PROSSTT?

Thanks!

**Comment by galicae** [comment]
Unfortunately, for the time being, we are not planning to include dropout as a PROSSTT feature. As things are right now, if you want to have dropout I would suggest doing something downstream of the simulation itself:

```
from scipy.stats import bernoulli

def naive_dropout(X):
    N, G = X.shape
    dropout_prob_per_gene = np.exp(random.normal(loc=np.log(0.1), scale=0.5, size=G))
    dropped_out = np.zeros((N, G), dtype=np.bool)
    dropout_picker = bernoulli(dropout_prob_per_gene)
    for n in range(N):
        dropped_out[n] = dropout_picker.rvs()

    drop_X = np.copy(X)
    drop_X[dropped_out] = 0
    return drop_X

X_prime = naive_dropout(your_simulated_data)
```

this code comes with the it-worked-on-my-machine warranty ;) Hope it can help as a stop-gap!

**Comment by scottgigante** [comment]
Thanks very much for that! I had hacked together my own solution but this is much more elegant.

**Comment by galicae** [comment]
glad I could help!
